### ISSUE TITLE
request header is not right: content-type is switched to 'application/x-www-form-urlencoded' 

### ISSUE THREAD

**Issue by dwguo** [bayashi/Amazon-PAApi5-Signature#1]
i installed it and just tested it out. i am getting an error:
<InternalFailure/>

i examined the request and saw the content-type is not right. as soon as i forced it to 
"application/json; charset=utf-8", the error went away.

Could you please fix it? 

Thank you!

**Comment by bayashi** [comment]
Hi @dwguo , could you please tell me your environment?
The versions of Perl and what modules did you use as HTTP Client?

**Comment by bayashi** [comment]
I've merged https://github.com/bayashi/Amazon-PAApi5-Signature/pull/2 and released it to CPAN.
Thanks, @cho45 and @dwguo .

Just in case, I added a workflow which exactly accesses to Amazon PA-API.
https://github.com/bayashi/Amazon-PAApi5-Signature/actions?query=workflow%3Aexample_script
