### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by stealthylabs** [bayashi/Amazon-PAApi5-Signature#12]
Hello @bayashi 
I tried using the package latest version and set up a script to use my partner tag, access key and secret key correctly. I requested 1 ASIN to test. I am using `us-east-1` and `webservices.amazon.com` as the required marketplace values.

However, I end up getting the 401 `Unauthorized` error, which I checked means that the signature is incorrect.

I did the same using the NodeJS SDK example that Amazon provides and it gives me a 429 error which is `Too Many Requests` and that makes sense, at least it is accepting the signature generated by the NodeJS SDK. And I am not against using that for my task at the moment but I prefer using Perl to cut and chop the results etc.

Trying to build a simple bot that can download some Amazon listings and then relist for affiliate marketing.

**Comment by stealthylabs** [comment]
seems like something is off with my code as I was using Mojo::UserAgent and I need to use LWP::UserAgent to make it work as in your example.

**Comment by bayashi** [comment]
@stealthylabs Hello. Thank you for using. Yeah, could you please [try this script](https://github.com/bayashi/Amazon-PAApi5-Signature/blob/master/example/us_getbrowsernode.pl) first? Then, try with your actual code. I'm not sure Mojo::UserAgent well though. It'd be able to work with, I guess. I'm looking forward a successful report. 👍

**Comment by stealthylabs** [comment]
@bayashi  that script worked fine and your script also worked fine. and in my script I used `LWP::UserAgent`, used  1 ASIN and it worked fine if the following `print` was not done before the request. Then you get the 401 error. So it seems that by calling `print` I am somehow changing the signature of the `$sig` object and that gives the 401 error below.

```
    my $sig = Amazon::PAApi5::Signature->new(
        $ACCESS_KEY,
        $SECRET_KEY,
        $payload,
        {
            operation => 'GetItems',
            host      => 'webservices.amazon.com',
            region    => 'us-east-1',
        },
    );
    print Dumper($sig->req_url), "\n";
    print Dumper($sig->headers), "\n";
    print $sig->payload, "\n";

    my $ua = LWP::UserAgent->new;

    my $req = POST $sig->req_url, $sig->headers, Content => $sig->payload;
    my $res = $ua->request($req);

    warn Dumper($res->status_line, $res->content);
```

```
`VAR1 = '401 Unauthorized';
$VAR2 = '{"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}';
`

**Comment by bayashi** [comment]
hm, I can't see a reason why you got 401 from the part of code. Anyway, it's okay to work. Thank you.
